# Generated by Django 3.2.9 on 2021-12-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.CharField(default='Description', max_length=255, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
