# Generated by Django 3.2.9 on 2021-12-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20211209_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='dish_menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='dish_menu',
            field=models.ManyToManyField(blank=True, to='restaurants.Dish'),
        ),
    ]
